<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="libLLVM.runtime.win-x64" Version="18.1.3.1" />
        <PackageReference Include="LLVMSharp" Version="18.1.0-rc1.8895972383" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\*.exe"/>
        <EmbeddedResource Include="Resources\libc\src\*.c"/>
        <EmbeddedResource Include="Resources\libc\src\*.h"/>
    </ItemGroup>

</Project>
