/*
Todo:
	- control flow
	- standardize mutability, references, pointers, etc.
	- pre-processor directives
	- memory management
	- macros?
	- nested comments
	- casting
	- lambdas
	- built-in casts
	- built-in operations (in progress)
	- string interpolation
	- pattern matching (even on types)
	- dependent types?
	- refinement types?
	- algebraic data types
	- algebraic effects?
	- side-effect tracking
	- ownership/borrowing akin to Rust
	- implicit return in entry point
	- allow explicit return type on entry point
	- add args to entry point
	- probably replace 'entry' keyword with 'fun main' special function signature
	- visibility/access modifiers
		(tls stands for 'top-level statements' and include types, external functions, functions, and constants
		- (none):
			- on tls: same as 'local'
			- in types: same as 'pub'
		- private:
			- on tls: only valid for nested types (if I add them); only visible to owning type; cannot be imported
			- in types: only visible to owning type
		- pub (public):
			- on tls: visible anywhere; may be imported
			- in types: visible anywhere
		- local: visible anywhere in the file it's declared in; cannot be imported
			- within a type marked with 'local', all 'pub' access is equivalent to 'local'
		- internal: visible in the top-most module it's declared in and its children modules; may be imported
			- if defined in 'mod.a.b', visible to 'mod' and all children of 'mod'
			- within a type marked with 'internal', all 'pub' access is equivalent to 'internal'
		- restricted: visible in the module it's declared in and its children modules; may be imported
			- if defined in 'mod.a.b', visible to 'mod.a.b' and all children of 'mod.a.b'
			- within a type marked with 'restricted', all 'pub' access is equivalent to 'restricted'
	- return type inference
	- default keyword
	- error on cyclic references
	- resolver should be able to determine constant expressions
	- move size resolution into resolver
		- utilize as many passes as needed until count of unresolved sizes reaches 0
		- keep track of already visited types; skip them
	- switch statement
		- if all cases are compile-time constants:
			- can be compiled directly to llvm ir
		- if all cases are types:
			- can be compiled directly to llvm ir because types have a unique numeric identifier that is constant
		- if some cases are compile-time constants:
			- create a switch statement with a case for each constant
			- create a default case that forms an if-else chain for the non-constant cases (final else for default case)
		- if no cases are compile-time constants:
			- form an if-else chain (final else for default case)
	- nullable function calls: doSomething?()
		- the '?' means the function is only called if it is not null (ex: the variable stores a lambda)
	- add '!' postfix unary operator that converts T? into T for remaining control flow branch
*/

mod hello.World

struct String
{
	text: string
	
	new(text: string)
	{
		this.text = text
	}
}

const StdIn = -10
const StdOut = -11
const StdErr = -12

const CodePageUTF8 = 65001u

import("kernel32.dll")
{
	var fun WriteConsole(handle: usize, buffer: string, charCount: u32, charsWritten: u32?, reserved: usize) =>
		external(entry = "WriteConsoleA")
		
	var fun SetConsoleOutputCodePage(codePage: u32) =>
		external(entry = "SetConsoleOutputCP")
		
	var fun GetConsoleOutputCodePage(): u32 =>
		external(entry = "GetConsoleOutputCP")
		
	var fun GetConsoleCodePage(): u32 =>
		external(entry = "GetConsoleCP")
		
	var fun GetLastError(): i32 =>
		external(entry = "GetLastError")
		
	fun GetStdHandle(handle: u32): usize =>
		external(entry = "GetStdHandle")
}

entry()
{
	SetConsoleOutputCodePage(CodePageUTF8)
	let stdOut = GetStdHandle(StdOut)
	WriteConsole(stdOut, "Hello, World!\n", 15u32, null, 0u64) // Todo: Infer size from target so u64 suffix can be dropped
	
	let str = String.new("This is a test\n")
	WriteConsole(stdOut, str.text, 16u32, null, 0u64)
	
	return 0
}