module bs.io.console

// 65001u = UTF8
var fun SetConsoleOutputEncoding(codePage:uint) => external(entry = "set_console_output_encoding")
fun GetConsoleOutputEncoding() :> uint => external(entry = "get_console_output_encoding")
var fun Print(text:string) => external(entry = "print")

/*var fun printLine(text:string)
{
	// Todo: Change to environment-specific newline once implemented
	print(text + "\n")
}*/